# Retro video games analysis: exploring the most popular video game remakes/remasters

## Introduction
The video game industry has seen a growing trend of remakes and remasters, driven by nostalgia, improved hardware, and renewed interest in classic titles. However, not all remasters achieve the same level of success. This project aims to understand what factors contribute to a successful retro video game remaster by comparing remastered games with their original releases. The insights gathered from the project would identify what features of retro games would best predict successful ports, leading to decisions on which retro games to port next for studios.

The datasets is from __[Kaggle: IMDB Video Games](https://www.kaggle.com/datasets/muhammadadiltalay/imdb-video-games)__ and contains data from IMDB for around 20k titles from 9 different genres. This dataset was then merged with a wikipedia table for remakes/remastered games list (this table was downloaded from this __[wikipedia page](https://en.wikipedia.org/wiki/List_of_video_game_remakes_and_remasters)__ and converted to csv format using the tool from this github repo: __[wikitable2csv](https://github.com/gambolputty/wikitable2csv)__. This was done so that we can partition the imdb dataset into remakes/remasters only.

## Table of contents

- Objectives
- Preparation
- Exploration
- Data cleaning and wrangling
- Analysis
- Visualisations
- Conclusions

## Objectives
Based on this dataset we want to ask the following questions:
- Which video game remasters have the highest ratings?
- Which genres produce the most successful remakes/remasters?
- Does higher votes and ratings of the original retro game lead to a more successful remake/remaster?

## Preparation
### Preparing the environment and loading the datasets
We will import the libraries required for the processing and load the datasets. The data will then be separated into raw and working dataframes in order preserve the original data and ensure safe experimentation.

In [3]:
# import libraries
import re
import pandas as pd
import numpy as np

# load datasets
df_imdb_raw = pd.read_csv("imdb_videogames.csv")
df_wiki_raw = pd.read_csv("wiki_list.csv")

In [4]:
# creating working dataframes
df_imdb = df_imdb_raw.copy()
df_wiki = df_wiki_raw.copy()

## Exploration
In this step we will view the basic structure of our dataframes

In [7]:
# view wiki remakes/remaster list first 3 rows
df_wiki.head(3)

,Title,Release year,Platform(s),Title.1,Release year.1,Platform(s).1,Enhancements,Ref(s)
0,1942,1984,Arcade,1942: Joint Strike,2008,"Xbox 360, PlayStation 3",Remake of the original game.,NaN
1,A Boy and His Blob: Trouble on Blobolonia,1989,NES,A Boy and His Blob,2009,"Wii, Xbox One, PlayStation 3, PlayStation 4, P...",Remake of the original game.,NaN
2,Ace Combat 2,1997,PlayStation,Ace Combat: Assault Horizon Legacy,2011,Nintendo 3DS,Remake of the original game.,NaN

In [8]:
df_imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20803 entries, 0 to 20802
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         20803 non-null  object
 1   url          20803 non-null  object
 2   year         20536 non-null  float64
 3   certificate  7903 non-null   object
 4   rating       11600 non-null  float64
 5   votes        11600 non-null  object
 6   plot         20803 non-null  object
 7   Action       20803 non-null  bool
 8   Adventure    20803 non-null  bool
 9   Comedy       20803 non-null  bool
 10  Crime        20803 non-null  bool
 11  Family       20803 non-null  bool
 12  Fantasy      20803 non-null  bool
 13  Mystery      20803 non-null  bool
 14  Sci-Fi       20803 non-null  bool
 15  Thriller     20803 non-null  bool
dtypes: bool(9), float64(2), object(5)
memory usage: 1.3+ MB

In [6]:
# view imdb data set first 3 rows
df_imdb.head(3)

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False

In [9]:
df_wiki.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743 entries, 0 to 742
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Title           743 non-null    object
 1   Release year    743 non-null    int64
 2   Platform(s)     743 non-null    object
 3   Title.1         743 non-null    object
 4   Release year.1  743 non-null    object
 5   Platform(s).1   743 non-null    object
 6   Enhancements    723 non-null    object
 7   Ref(s)          1 non-null      object
dtypes: int64(1), object(7)
memory usage: 46.6+ KB

### Renaming columns of wiki table
The wikipedia table column names will be renamed to more clear titles (after standardising)

In [19]:
# standardising wiki table column names
df_wiki.columns = (
    df_wiki.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

In [20]:
df_wiki = df_wiki.rename(columns={
    "title": "original_title",
    "title.1": "remaster_title",
    "release_year" : "original_release_year",
    "release_year.1" : "remaster release year",
    "platform(s)" : "original_platform",
    "platform(s).1" : "remaster_platform" 
})

In [21]:
df_wiki.head(3)

,original_title,original_release_year,original_platform,remaster_title,remaster release year,remaster_platform,enhancements,ref(s)
0,1942,1984,Arcade,1942: Joint Strike,2008,"Xbox 360, PlayStation 3",Remake of the original game.,NaN
1,A Boy and His Blob: Trouble on Blobolonia,1989,NES,A Boy and His Blob,2009,"Wii, Xbox One, PlayStation 3, PlayStation 4, P...",Remake of the original game.,NaN
2,Ace Combat 2,1997,PlayStation,Ace Combat: Assault Horizon Legacy,2011,Nintendo 3DS,Remake of the original game.,NaN

# Data cleaning and wrangling
The idea of this analysis is to have data for both the original and corresponding remake side by side as one entry in a dataframe. This will allow us to compare votes and rating for each retro game vs its remake/remaster. The relavent titles will (accurately) be retrieved from the imdb list using fuzzy matching, by matching for title AND release year.

In [25]:
# standardising column names
df_imdb.columns = (
    df_imdb.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

In [28]:
# cleaning title names function
def clean_title(title):
    title = title.lower().strip()
    # Remove trademark symbols
    title = re.sub(r'™|®', '', title)
    # Replace colon, dash, HD, remastered, remake with a SPACE
    title = re.sub(r':| - | hd| remastered| remake', ' ', title)
    # Remove anything in parentheses
    title = re.sub(r'\(.*?\)', '', title)
    # Remove all other non-alphanumeric characters but keep spaces
    title = re.sub(r'[^a-z0-9 ]', '', title)
    # Replace multiple spaces with a single space
    title = re.sub(r'\s+', ' ', title)
    return title.strip()

In [30]:
# create cleaned titles using clean_title function
df_imdb["clean_title"] = df_imdb["name"].apply(clean_title)
df_wiki["clean_title_og"] = df_wiki["original_title"].apply(clean_title)
df_wiki["clean_title_rm"] = df_wiki["remaster_title"].apply(clean_title)

In [31]:
# splitting imdb data into original and remasters/remakes
remaster_keywords = ["remaster", "remastered", "remake", "hd", "anniversary", "definitive", "collection"]

In [32]:
# converting year column from float to int64 (supports null values) 
df_imdb["year"] = pd.to_numeric(df_imdb["year"], errors="coerce").astype("Int64")

In [33]:
# checking for NaN and empty strings in cleaned titles for imdb_remaster and imdb_normal_games
df_imdb[df_imdb["clean_title"].isna() | (df_imdb["clean_title"] == "")]

,name,url,year,certificate,rating,votes,plot,action,adventure,comedy,crime,family,fantasy,mystery,sci-fi,thriller,clean_title
17494,>=<,https://www.imdb.com/title/tt10345886/?ref_=ad...,2010,NaN,NaN,NaN,Add a Plot,False,False,False,False,True,False,False,False,False,

In [63]:
df_imdb["votes"] = (
    df_imdb["votes"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

In [73]:
df_imdb["votes"] = pd.to_numeric(df_imdb["votes"], errors="coerce").astype("Int64")

In [68]:
# function to add column to dataframe with either true or false if clean title has any of the remaster keywords in it (using regular expressions)
pattern = r"\b(?:{})\b".format("|".join(remaster_keywords))

df_imdb["is_remaster"] = (
    df_imdb["clean_title"]
    .str.contains(pattern, regex=True, na=False))

In [69]:
# partioning imdb dataset into seperate dataframes for remasters/remakes and non remastered games
imdb_normal_games = df_imdb[df_imdb["is_remaster"] == False]
imdb_remasters = df_imdb[df_imdb["is_remaster"] == True]

In [ ]:
imdb_normal_games.info()

In [ ]:
# randomly selecting records (spot check)
df_imdb.sample(20)

In [113]:
# creating column with unique imdb url text identifier
df_imdb["imdb_id"] = df_imdb["url"].str.extract(r"(tt\d+)")

In [122]:
# deduplicating for imdb entries with same ids in url
df_imdb = (
    df_imdb.sort_values("votes", ascending=False)
      .drop_duplicates(subset=["imdb_id"], keep="first")
)

In [123]:
# validating
df_imdb["imdb_id"].is_unique

True

In [127]:
# rechecking for clean_title and year duplicates
df_imdb["clean_title"].value_counts().loc[lambda x: x > 1].head(10)

clean_title
star trek                         6
batman                            5
spiderman                         5
spiderman 2                       5
the terminator                    5
shadowrun                         4
jurassic park                     4
monopoly                          4
star wars                         4
the adventures of batman robin    4
Name: count, dtype: int64

In [132]:
# spot checking duplicates again after removing imdb id duplicates
df_imdb.loc[
    (df_imdb["clean_title"] == "star trek"),
    ["name", "year", "votes", "rating", "imdb_id", "url"]
]

,name,year,votes,rating,imdb_id,url
787,Star Trek,2013,946,6.9,tt2191526,https://www.imdb.com/title/tt2191526/?ref_=adv...
20000,Star Trek,1991,115,6.9,tt0152592,https://www.imdb.com/title/tt0152592/?ref_=adv...
19671,Star Trek,1983,51,7.5,tt0475733,https://www.imdb.com/title/tt0475733/?ref_=adv...
19570,Star Trek,1971,28,6.9,tt1982844,https://www.imdb.com/title/tt1982844/?ref_=adv...
5003,Star Trek,1972,15,5.4,tt1982161,https://www.imdb.com/title/tt1982161/?ref_=adv...
20593,Star Trek,1991,<NA>,NaN,tt14545272,https://www.imdb.com/title/tt14545272/?ref_=ad...

In [133]:
# checking how many entries with same titles and year
df_imdb.duplicated(subset=["clean_title", "year"]).sum()

64

## Limitations
This dataset had no sales data available. Sales data is a key metric for analysing remake/remaster success.